server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: "elysiawain"
    # druid-spring-boot-starter 依赖自动生效 druid，可以不配置 type 属性，但建议配置
    type: com.alibaba.druid.pool.DruidDataSource
    graphiql:
      enabled: true
 #邮箱验证码
  mail:
    host: smtp.163.com
    port: 587
    username: tangwuji20040212@163.com
    password: AIKVZPGRLYTNMCTR
    default-encoding: UTF-8
    protocol: smtps
    properties:
      mail:
        transport:
          protocol: smtps
        smtp:
          ssl:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      #基于jedis
      jedis:
        pool:
          max-active:  8 #最大连接数
          max-idle: 4 #连接池中最大的 idle 状态（空闲）连接数
          min-idle: 0 #最小
          max-wait: -1ms

#配置redis

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
#配置mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    开启自动补齐驼峰
    map-underscore-to-camel-case: true

logging:
  level:
    com.chz.mapper: debug

#配置阿里云oss

